name: run top50 CSV 
on:
  schedule:
    - cron: "15 09 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycoingecko
          pip install numpy
          pip install pandas
          pip install requests
          pip install datetime

      - name: Run the script
        run: python updatetop50.py

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit and Push changes
        env:
          SECRETTT: ${{ secrets.SECRETTT }}
        run: |
          git remote set-url origin "https://${{ secrets.SECRETTT }}@github.com/ltthangds86/momentumcrypto.git"
          git add .
          git commit -m "Update top50 CSV file"
          git push origin main


